$axure.loadCurrentPage({
  "url":"乘客版.html",
  "generationDate":new Date(1514895969913),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9370733c35f4087801aebc565ea84e6",
    "type":"Axure:Page",
    "name":"乘客版",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"643ee50c4aff495aba371b5e41529d24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebaf98111e064cbab2b8c42e17dbe999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/乘客版/u0.png"}},
{
          "id":"7a289450f3134a6f8934e9fad87e356a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":116},
            "size":{
              "width":320,
              "height":44},
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a78f70db66af47c8bbfe93627e97e857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":116},
                "size":{
                  "width":320,
                  "height":44},
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/乘客版/u2.png"}},
{
          "id":"725e056c0a664d37bb35463fffcfbebc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":130},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea86b99da5df49f9949cea4b635c14f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":130},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/乘客版/u4.png"}},
{
          "id":"1e087e3cddd14bd2b3b693fccf362827",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":180},
            "size":{
              "width":310,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4a1d9c68eb45b1aab503cd39ede232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":180},
                "size":{
                  "width":310,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/乘客版/u6.png"}},
{
          "id":"5c6ad8a7e3d6458594e914b56ae8c9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":60,
              "y":214},
            "size":{
              "width":250,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f709f2981884f40b8c34d6d8626b5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":60,
                  "y":214},
                "size":{
                  "width":250,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caa9052b92be4e85aa0c25b2fb9e9d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":60,
              "y":252},
            "size":{
              "width":250,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7488771d6ff4e5682f99dc9c894723a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":252},
                "size":{
                  "width":250,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13d01cfb1a6941e8b227dc44a492d9e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF797979},
            "location":{
              "x":50,
              "y":310},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d189f46c37fd43e29fc6869e2cef40f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF797979},
                "location":{
                  "x":50,
                  "y":310},
                "size":{
                  "width":280,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/乘客版/u12.png"}},
{
          "id":"aaa290a9cb33454db988af76eb64fc20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":148,
              "y":321},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d5d52fd807f4ff1ae73500373eb8534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":321},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "643ee50c4aff495aba371b5e41529d24":{
      "scriptId":"u0"},
    "ebaf98111e064cbab2b8c42e17dbe999":{
      "scriptId":"u1"},
    "7a289450f3134a6f8934e9fad87e356a":{
      "scriptId":"u2"},
    "a78f70db66af47c8bbfe93627e97e857":{
      "scriptId":"u3"},
    "725e056c0a664d37bb35463fffcfbebc":{
      "scriptId":"u4"},
    "ea86b99da5df49f9949cea4b635c14f6":{
      "scriptId":"u5"},
    "1e087e3cddd14bd2b3b693fccf362827":{
      "scriptId":"u6"},
    "aa4a1d9c68eb45b1aab503cd39ede232":{
      "scriptId":"u7"},
    "5c6ad8a7e3d6458594e914b56ae8c9dc":{
      "scriptId":"u8"},
    "0f709f2981884f40b8c34d6d8626b5e5":{
      "scriptId":"u9"},
    "caa9052b92be4e85aa0c25b2fb9e9d12":{
      "scriptId":"u10"},
    "d7488771d6ff4e5682f99dc9c894723a":{
      "scriptId":"u11"},
    "13d01cfb1a6941e8b227dc44a492d9e9":{
      "scriptId":"u12"},
    "d189f46c37fd43e29fc6869e2cef40f3":{
      "scriptId":"u13"},
    "aaa290a9cb33454db988af76eb64fc20":{
      "scriptId":"u14"},
    "1d5d52fd807f4ff1ae73500373eb8534":{
      "scriptId":"u15"}}});